spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/** 
        - id: flight
          uri: http://localhost:8082
          predicates:
            - Path=/flights/** #/viewOrderDetails/**
        - id: pay
          uri: http://localhost:8083
          predicates:
            - Path=/pays/** 
#        - id: order
#          uri: http://localhost:8082
#          predicates:
#            - Path=/orders/**
#        - id: product
#          uri: http://localhost:8081
#          predicates:
#            - Path=/products/**
---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://cloud:8082
          predicates:
            - Path=/orders/**
        - id: product
          uri: http://cloud:8081
          predicates:
            - Path=/products/**
api:
  url:
    product: http://flights:8080
---
spring:
  profiles: cloud
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://cloud:8082
          predicates:
            - Path=/orders/**
        - id: product
          uri: http://cloud:8081
          predicates:
            - Path=/products/**